### ISSUE TITLE
Failed to run the Upload recipe

### ISSUE THREAD

**Issue by agomas** [rogerclarkmelbourne/Arduino_STM32#330]
Hi,

I'm trying to upload a sketch I'm getting this error:

eclipse.buildId=unknown
java.version=1.8.0_131
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=pt_PT
Framework arguments:  -perspective io.sloeber.application.perspective -perspective io.sloeber.application.perspective
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -perspective io.sloeber.application.perspective -data file:/E:/sloeber-workspace/ -perspective io.sloeber.application.perspective

io.sloeber.arduino.core
Error
Fri Aug 25 15:57:24 BST 2017
Failed to run the Upload recipe 

java.io.IOException: Cannot run program "" (in directory "E:\sloeber-workspace"): CreateProcess error=87, O parâmetro está incorreto
	at java.lang.ProcessBuilder.start(Unknown Source)
	at io.sloeber.core.tools.ExternalCommandLauncher.launch(ExternalCommandLauncher.java:294)
	at io.sloeber.core.tools.uploaders.GenericLocalUploader.RunConsoledCommand(GenericLocalUploader.java:40)
	at io.sloeber.core.tools.uploaders.arduinoUploader.uploadUsingPreferences(arduinoUploader.java:82)
	at io.sloeber.core.tools.uploaders.UploadSketchWrapper$UploadJobWrapper.run(UploadSketchWrapper.java:177)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: CreateProcess error=87, O parâmetro está incorreto
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 6 more

Follows the properties:
![sloeber](https://user-images.githubusercontent.com/31351097/29719847-bd857a7a-89af-11e7-8e95-0885a145421d.png)

I'm using the bluepill. I have now problems in a computer with an earlier installation, but now I'm trying to install all the environment to program the bluepill in other computers and the error is always the same.

I have tried the other solutions in the issue #714, but the error is the same.

What is missing?

Thank you in advance.

Regards

**Comment by rogerclarkmelbourne** [comment]
Only the official Arduino IDE is supported
